### ISSUE TITLE
Translate Array and Detect Array is missing

### ISSUE THREAD

**Issue by shanmuk** [relrod/bing_translator-gem#12]
As the bing API is providing translate array method its better to have one method for array to avoid bulk API calls.

http://msdn.microsoft.com/en-us/library/ff512407.aspx

A sampling of the methods that the API provides to the developer are listed below:

Translate — Translates text from one language to another
TranslateArray — Translates an array of texts from one language to another
Speak (Text to Speech) — Returns audio of the text spoken in the desired language
Detect — Detects the language of the string
Detect Array — Detects the language of an array of strings
GetTranslations — Returns an array of alternative translations for the text
GetTranslationsArray — Returns an array of alternative translations for a text array
GetLanguageNames, GetLanguagesForSpeak, GetLanguagesForTranslate — Return a list of languages supported by name, for audio and by code
AddTranslation, AddTranslationArray — Allows developers to add their own translations to the Microsoft Translator infrastructure.

**Comment by relrod** [comment]
Hi, if this is still something you'd like, could you send it as a proper pull request against `master`? I'm going to close this out for now to bump it out of my queue.
