### ISSUE TITLE
 undefined method `headers' for HTTP:Module (BingTranslator::Exception)

### ISSUE THREAD

**Issue by Beat-Nick** [relrod/bing_translator-gem#23]
As ruby novice I can't sort out the error I receive when using the basic code shown in the documentation. I was hoping someone could point me in the right direction

    require 'bing_translator'

    auth = YAML.load_file('bing_translate.yml')
    translator = BingTranslator.new(auth['client_id'],auth['client_secret'],false,auth['azure_key'])

    #This works great so I'm authorized and talking to the API
    puts translator.balance

    #This code here kicks out the exception
    spanish = translator.translate('Hello. This will be translated!', :from => 'en', :to => 'es')
    puts spanish

 undefined method 'headers' for HTTP:Module (BingTranslator::Exception)
from /usr/local/rvm/gems/ruby-2.2.1/gems/bing_translator-4.4.1/lib/bing_translator.rb:158:in 'result
from /usr/local/rvm/gems/ruby-2.2.1/gems/bing_translator-4.4.1/lib/bing_translator.rb:45:in 'translate'

**Comment by relrod** [comment]
I can't reproduce this, but doing some searching, try adding `httpclient` to your Gemfile? Not sure off hand, maybe @tsion has an idea.

**Comment by Beat-Nick** [comment]
@relrod installing the httpclient gem fixed my issue. The translations work just fine now. Thanks for all the help!
