### ISSUE TITLE
bad URI(is not URI?)

### ISSUE THREAD

**Issue by dudleysr** [relrod/bing_translator-gem#24]
Getting an error when attempting to use the translate method. I can create a translator and get my balance but the actual translate method returns this error:

`BingTranslator::Exception: bad URI(is not URI?): {:host=>"api.microsofttranslator.com", :path=>"/V2/soap.svc", :port=>"80", :query=>"wsdl", :scheme=>"http", :headers=>{}, :body=>nil, :ssl_verify_peer=>true}`

**Comment by relrod** [comment]
I'm not immediately able to reproduce this. Is there a stack trace you could post? What OS and version of Ruby?

**Comment by dudleysr** [comment]
I am running Ruby 1.9.3p545, OSX 10.10.5. I was just running it in Rails Console, but here's the error I get:
```
[4] pry(main)> translator.translate('Hello.', :from => 'en', :to => 'es')
BingTranslator::Exception: bad URI(is not URI?): {:host=>"api.microsofttranslator.com", :path=>"/V2/soap.svc", :port=>"80", :query=>"wsdl", :scheme=>"http", :headers=>{}, :body=>nil, :ssl_verify_peer=>true}
from /Users/scott/Code/metrics/vendor/bundle/gems/bing_translator-4.5.0/lib/bing_translator.rb:179:in `rescue in result'
```
