### ISSUE TITLE
How to test code using the bing_translator gem?

### ISSUE THREAD

**Issue by andneuma** [relrod/bing_translator-gem#32]
Hey there,

maybe not the best place but I cannot find any other. First of all: Thanks for the gem, makes my life a lot easier dealing with the bing API. Now, in an application I want to mock the response coming from the service in order to write some some tests for a wrapper I've built around your gem. Is there any possiblity to do that **without** setting up a test API key calling the API every time I'm running a bing-related test?

best and thanks,
Andi

**Comment by abrisse** [comment]
Hi,

If you make a wrapper around the gem you should mock the `BingTranslator` class in your test (for example with `instance_double(BingTranslator, translate: translation)`.

That way you don't need any API key.
