### ISSUE TITLE
Are you releasing 5.0.0?

### ISSUE THREAD

**Issue by absessive** [relrod/bing_translator-gem#33]
The 5.0.0 tag which uses the new COGNITIVE_SUBSCRIPTION_KEY isn't released. Is there plans to release this? The docs or page are useless as 4.6.0 seems obsolete.

**Comment by solson** [comment]
I pushed 5.0.0: https://rubygems.org/gems/bing_translator/versions/5.0.0

Let me know if there are any problems with it.
