### ISSUE TITLE
Abbreviations?

### ISSUE THREAD

**Issue by monroemann** [relrod/bing_translator-gem#41]
Hello Rick!  @relrod 

Thanks for creating this.  Do you have a list of all the abbreviations for the languages?

Also, can this easily be used to offer a 'translate' button in a forum, and when pressed, it asks which language you want it translated into, and then it translates the text?  

Thanks!
-Monroe

**Comment by abrisse** [comment]
List is available on https://docs.microsoft.com/en-us/azure/cognitive-services/translator/languages

Sure, you can use this gem to provide such service
